const assert=require("node:assert");
const fs=require("node:fs");
const path=require("node:path");
const pkg=require("../package.json");
const server=fs.readFileSync(path.join(__dirname,"server.js"),"utf8");
const html=fs.readFileSync(path.join(__dirname,"../public/index.html"),"utf8");
assert.strictEqual(pkg.version,"10.0.0");
assert.ok(pkg.scripts.start);
assert.ok(pkg.scripts.check);
assert.ok(pkg.scripts.smoke);
assert.ok(fs.existsSync(path.join(__dirname,"server.js")));
assert.ok(fs.existsSync(path.join(__dirname,"../public/index.html")));
assert.ok(server.includes('app.get("/api/ping"'));
assert.ok(server.includes('app.get("/api/health"'));
assert.ok(server.includes('app.get("/api/ready"'));
assert.ok(server.includes('app.get("/api/market"'));
assert.ok(server.includes('wss'));
assert.ok(html.includes('/api/market'));
console.log("industrial v10 structure and critical routes: OK");
